# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Heath Line' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Heath Line
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase'
  pod 'FirebaseCore'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'DropDown', :git=> 'https://github.com/AssistoLab/DropDown.git'

  target 'Heath LineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Heath LineUITests' do
    # Pods for testing
  end

end
